version: '3.6'

services:
  node:
    container_name: coder_node_1
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./source:/app/source
      - ./.env:/app/.env